from liveness_analysis import LIVE_VALUES, instruction_use_def


class ReachingDefinitionError(ValueError):
    pass


def _definition_id(address, value):
    return f"D{address:05X}:{value}"


def _entry_definition_id(entry, value):
    return f"E{entry:05X}:{value}"


def _function_entries(nodes, edges, entry_address):
    by_address = {node["address"]: node for node in nodes}
    entries = set()
    if entry_address in by_address:
        entries.add(entry_address)
    entries.update(
        edge["target"]
        for edge in edges
        if edge.get("kind") == "call"
        and edge.get("resolved")
        and edge.get("target") in by_address
    )
    return sorted(entries)


def _predecessors(nodes, edges):
    by_address = {node["address"]: node for node in nodes}
    predecessors = {address: set() for address in by_address}
    for edge in edges:
        if (
            not edge.get("resolved")
            or edge.get("target") not in by_address
            or edge.get("source") not in by_address
            or edge.get("kind") == "call"
            or edge.get("synthetic_return")
        ):
            continue
        predecessors[edge["target"]].add(edge["source"])
    return predecessors


def _empty_state():
    return {value: set() for value in LIVE_VALUES}


def _copy_state(state):
    return {value: set(state.get(value, ())) for value in LIVE_VALUES}


def _state_equal(left, right):
    return all(set(left.get(value, ())) == set(right.get(value, ())) for value in LIVE_VALUES)


def analyze_reaching_definitions(nodes, edges, entry_address, summaries=None, liveness=None):
    """Compute forward reaching definitions and deterministic def-use chains.

    Calls are summarized at the caller instruction, matching liveness and exact/range
    analysis: the call edge itself is not a forward dataflow edge, while the normal
    call fallthrough receives definitions generated by JSUB and the callee summary.
    Every statically discovered function entry receives pseudo-definitions for all
    tracked values, representing values supplied by an unknown caller/environment.
    """
    by_address = {node["address"]: node for node in nodes}
    if len(by_address) != len(nodes):
        raise ReachingDefinitionError("Duplicate typed instruction address")

    entries = _function_entries(nodes, edges, entry_address)
    predecessors = _predecessors(nodes, edges)
    semantics = {
        address: instruction_use_def(node, summaries=summaries)
        for address, node in by_address.items()
    }

    definitions = {}
    entry_definitions = {}
    for entry in entries:
        entry_definitions[entry] = {}
        for value in LIVE_VALUES:
            definition_id = _entry_definition_id(entry, value)
            entry_definitions[entry][value] = definition_id
            definitions[definition_id] = {
                "id": definition_id,
                "kind": "entry",
                "address": entry,
                "value": value,
                "function_entry": entry,
            }

    generated = {}
    for address in sorted(by_address):
        generated[address] = {}
        for value in semantics[address]["defs"]:
            definition_id = _definition_id(address, value)
            generated[address][value] = definition_id
            definitions[definition_id] = {
                "id": definition_id,
                "kind": "instruction",
                "address": address,
                "value": value,
                "function_entry": None,
            }

    reaching_in = {address: _empty_state() for address in by_address}
    reaching_out = {address: _empty_state() for address in by_address}
    ordered = sorted(by_address)
    changed = True
    while changed:
        changed = False
        for address in ordered:
            incoming = _empty_state()
            for predecessor in predecessors[address]:
                for value in LIVE_VALUES:
                    incoming[value] |= reaching_out[predecessor][value]
            for value, definition_id in entry_definitions.get(address, {}).items():
                incoming[value].add(definition_id)

            outgoing = _copy_state(incoming)
            for value, definition_id in generated[address].items():
                outgoing[value] = {definition_id}

            if not _state_equal(incoming, reaching_in[address]) or not _state_equal(outgoing, reaching_out[address]):
                reaching_in[address] = incoming
                reaching_out[address] = outgoing
                changed = True

    def_use = {definition_id: [] for definition_id in definitions}
    instruction_facts = {}
    unresolved_uses = []
    for address in ordered:
        use_definitions = {}
        unresolved = []
        for value in semantics[address]["uses"]:
            reaching = sorted(reaching_in[address][value])
            use_definitions[value] = reaching
            if not reaching:
                unresolved.append(value)
                unresolved_uses.append({"address": address, "value": value})
            for definition_id in reaching:
                def_use[definition_id].append({"address": address, "value": value})

        instruction_facts[address] = {
            "reaching_in": {
                value: sorted(reaching_in[address][value])
                for value in LIVE_VALUES
                if reaching_in[address][value]
            },
            "reaching_out": {
                value: sorted(reaching_out[address][value])
                for value in LIVE_VALUES
                if reaching_out[address][value]
            },
            "use_definitions": use_definitions,
            "definition_ids": dict(sorted(generated[address].items())),
            "unresolved_uses": sorted(unresolved),
        }

    chains = []
    for definition_id in sorted(definitions):
        definition = definitions[definition_id]
        uses = sorted(def_use[definition_id], key=lambda item: (item["address"], item["value"]))
        chains.append({**definition, "use_sites": uses})

    dead_definitions = []
    if liveness is not None:
        for address in ordered:
            facts = liveness.get(address, {})
            for value in facts.get("dead_writes") or ():
                definition_id = generated[address].get(value)
                if definition_id is not None:
                    dead_definitions.append({
                        "definition_id": definition_id,
                        "address": address,
                        "value": value,
                        "use_sites": list(def_use[definition_id]),
                    })
            if facts.get("dead_condition_write"):
                definition_id = generated[address].get("CC")
                if definition_id is not None:
                    dead_definitions.append({
                        "definition_id": definition_id,
                        "address": address,
                        "value": "CC",
                        "use_sites": list(def_use[definition_id]),
                    })

    return {
        "entries": entries,
        "entry_definitions": entry_definitions,
        "definitions": [definitions[key] for key in sorted(definitions)],
        "chains": chains,
        "instruction_facts": instruction_facts,
        "unresolved_uses": sorted(unresolved_uses, key=lambda item: (item["address"], item["value"])),
        "dead_definitions": sorted(dead_definitions, key=lambda item: (item["address"], item["value"])),
    }


def enrich_function_contracts(functions, reaching):
    """Attach conservative input/output contracts to discovered function objects.

    required_inputs are entry pseudo-definitions that feed an explicit use in the
    function body. passthrough_inputs reach every represented RSUB unchanged.
    overwritten_inputs reach no represented RSUB. produced_outputs are values with
    at least one local instruction definition reaching a represented return site.
    Functions without represented returns do not claim return-state contracts.
    """
    facts = reaching.get("instruction_facts", {})
    chains = {chain["id"]: chain for chain in reaching.get("chains", ())}
    entry_definitions = reaching.get("entry_definitions", {})
    definitions = {item["id"]: item for item in reaching.get("definitions", ())}

    for function in functions:
        entry = function["entry"]
        body = set(function.get("instruction_addresses") or ())
        returns = list(function.get("return_sites") or ())
        entry_defs = entry_definitions.get(entry, {})

        required = []
        input_use_sites = {}
        for value, definition_id in sorted(entry_defs.items()):
            sites = sorted({
                use["address"]
                for use in chains.get(definition_id, {}).get("use_sites", ())
                if use["address"] in body
            })
            if sites:
                required.append(value)
                input_use_sites[value] = sites

        passthrough = []
        overwritten = []
        partial = []
        produced = []
        output_definitions = {}
        if returns:
            for value, entry_definition in sorted(entry_defs.items()):
                reaches = [
                    entry_definition in set(facts.get(site, {}).get("reaching_in", {}).get(value, ()))
                    for site in returns
                ]
                if all(reaches):
                    passthrough.append(value)
                elif any(reaches):
                    partial.append(value)
                else:
                    overwritten.append(value)

            for value in LIVE_VALUES:
                local_definitions = set()
                for site in returns:
                    for definition_id in facts.get(site, {}).get("reaching_in", {}).get(value, ()):
                        definition = definitions.get(definition_id)
                        if (
                            definition is not None
                            and definition.get("kind") == "instruction"
                            and definition.get("address") in body
                        ):
                            local_definitions.add(definition_id)
                if local_definitions:
                    produced.append(value)
                    output_definitions[value] = sorted(local_definitions)

        function["required_inputs"] = sorted(required)
        function["input_use_sites"] = input_use_sites
        function["passthrough_inputs"] = sorted(passthrough)
        function["partially_preserved_inputs"] = sorted(partial)
        function["overwritten_inputs"] = sorted(overwritten)
        function["produced_outputs"] = sorted(produced)
        function["output_definitions"] = output_definitions

    return functions
